version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

